lang = {
    'index1': {
        'lang': 'ru',
        'title': 'Блог',
        'head': 'Блог ',
        'readBlog': 'Читать блог',
        'logon': 'Вход',
        'registration': 'Регистрироваться',
    },
    'registration': {
        'lang': 'ru',
        'title': 'Регистрация',
        'head': 'Регистрация',
        'firstName': 'Имя',
        'lastName': 'Фамилия',
        'login': 'Логин',
        'password': 'Пароль',
        'avatar': 'Аватар',
        'btnRegistration': 'Регистрироваться',
    },
    'logon': {
        'lang': 'ru',
        'title': 'Авторизация',
        'head': 'Авторизация',
        'home': 'Главная',
        'login': 'Пользователь',
        'password': 'Пароль',
        'logon': 'Вход',
    },
    'adminPosts': {
        'lang': 'ru',
        'title': 'Редактор постов',
        'head': 'Редактор постов',
        'hi': 'Добро пожаловать',
        'logout': 'Выход',
        'create': 'Создать',
        'listBlogs': 'Посты:',
        'sandboxLabel': 'Песточница',
        'countText': 'Всего постов: ',
        'btnDelete': 'Удалить',
        'btnEdit': 'Редактировать',
    },
    'createPost': {
        'lang': 'ru',
        'title': 'Создать пост',
        'head': 'Создать пост',
        'post': 'Пост',
        'labelSandbox': 'Песочница',
        'send': 'Отправить',
    },
    'editPost': {
        'lang': 'ru',
        'title': 'Редактировать пост',
        'head': 'Редактировать пост',
        'body': 'Пост',
        'send': 'Отправить',
        'labelSandbox': 'Песточница',
        'labelDateCreate': 'Дата создания:',
        'labelDateEdit': 'Дата редактирования:',
    },
    'pageReadBlog':{
        'lang': 'ru',
        'title': 'Блог ',
        'head': 'Блог',
        'home': 'Главная',
        'listBlogs': 'Посты:',
        'countText': 'Всего постов: ',
        'btnRead': 'Читать',
    },
    'pageReadPost': {
        'lang': 'ru',
        'title': 'Пост ',
        'head': 'Блог',
        'home': 'Главная',
        'listBlogs': 'Вернуться к списку постов',
        'return': 'Вернуться',
        'countText': 'Всего постов: ',
        'btnRead': 'Читать',
    },
    'serverErr': {
        500: '500 ошибка сервера',
        404: '404 страница не найдена',
        },
}