lang = {
    'index1': {
        'lang': 'ru',
        'title': 'Админка',
        'head': 'Авторизация',
        'readBlog': 'Читать блог',
        'logon': 'Вход',
        'registration': 'Регистрироваться',
    },
    'registration': {
        'lang': 'ru',
        'title': 'Регистрация',
        'head': 'Регистрация',
        'firstName': 'Имя',
        'lastName': 'Фамилия',
        'login': 'Логин',
        'password': 'Пароль',
        'avatar': 'Аватар',
        'btnRegistration': 'Регистрироваться',
    },
    'logon': {
        'lang': 'ru',
        'title': 'Админка',
        'head': 'Авторизация',
        'home': 'Главная',
        'login': 'Пользователь',
        'password': 'Пароль',
        'logon': 'Вход',
    },
    'adminPosts': {
        'lang': 'ru',
        'title': 'Редактор постов',
        'head': 'Редактор постов',
        'hi': 'Добро пожаловать',
        'logout': 'Выход',
        'create': 'Создать',
        'listBlogs': 'Посты:',
        'sandboxLabel': 'Песточница',
        'countText': 'Всего постов: ',
        'btnDelete': 'Удалить',
        'btnEdit': 'Редактировать',
    },
    'createPost': {
        'lang': 'ru',
        'title': 'Создать пост',
        'head': 'Создать пост',
        'post': 'Пост',
        'labelSandbox': 'Песочница',
        'send': 'Отправить',
    },
    'editPost': {
        'lang': 'ru',
        'title': 'Редактировать пост',
        'head': 'Редактировать пост',
        'body': 'Пост',
        'send': 'Отправить',
        'labelSandbox': 'Песточница',
        'labelDateCreate': 'Дата создания:',
        'labelDateEdit': 'Дата редактирования:',
    },
    'blogsRead':{
        'lang': 'ru',
        'title': 'Блог',
        'head': 'Блог',
        'home': 'Главная',
        'listBlogs': 'Посты:',
        'countText': 'Всего постов: ',
        'btnRead': 'Читать',
    },
    'blogRead': {
        'lang': 'ru',
        'title': 'Блог',
        'head': 'Блог',
        'home': 'Главная',
        'listBlogs': 'Вернуться к списку постов',
        'countText': 'Всего постов: ',
        'btnRead': 'Читать',
    },
    # 'lang': 'ru',
    # 'titleAdmin': 'Админка',
    # 'headAdmin': 'Авторизация',
    # 'homePage': 'Главная',
    # 'login': 'Пользователь',
    # 'password': 'Пароль',
    # # 'logon': 'Вход',
    # 'titleEdit': 'Редактор постов',
    # 'headEdit': 'Редактор постов',
    # 'hi': 'Добро пожаловать',
    # 'logout': 'Выход',
    # 'create': 'Создать',
    # 'listBlogs': 'Посты:',
    # 'sandboxLabel': 'Песточница',
    # 'countPost': 'Всего постов: ',
    # 'btnDelete': 'Удалить',
    # 'btnEdit': 'Редактировать',
    # 'btnRead': 'Читать',
    # 'menuListPosts': 'Вернуться к списку постов',
    # 'titleCreatPost': 'Создать пост',
    # 'headCreatPost': 'Создать пост',
    # 'post': 'Пост',
    # 'labelSandbox': 'Песочница',
    # 'btnSend': 'Отправить',
    # 'title': 'Регистрация',
    # 'head': 'Форма регистрации',
    # 'firstName': 'Имя',
    # 'lastName': 'Фамилия',
    # 'avatar': 'Аватар',
    # 'titleEditPost': 'Редактировать пост',
    # 'headEditPost': 'Редактировать пост',
    # 'body': 'Пост',
    # 'send': 'Отправить',
    # 'labelDateCreate': 'Дата создания:',
    # 'labelDateEdit': 'Дата редактирования:',
    'serverErr': {
        500: '500 ошибка сервера',
        404: '404 страница не найдена',
        },
}